main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

story/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('aboutme/', include('aboutme.urls')),
    path('experience/', include('experience.urls')),
    path('story1/', include('story1.urls')),
    path('kuliah/', include('kuliah.urls')),
    path('kegiatan/', include('formulir.urls')),
    path('accordion/', include('accordion.urls')),
    path('story8/', include('story8.urls')),
    path('userauth/', include('userauth.urls')),
]

userauth/urls.py
from django.urls import path
from .views import userlogin, userregister, userlogout

app_name = 'userauth'

urlpatterns = [
	path('login/', userlogin, name = 'login'),
	path('register/', userregister, name = 'register'),
    path('logout/', userlogout, name = 'logout'),
]

userauth/models.py
from django.db import models

# Create your models here.

userauth/forms.py
from django import forms

class AuthForm(forms.Form):
    nama = forms.CharField(
        max_length = 300,
        widget = forms.TextInput(
            attrs = {
                'class': 'form-control',
				'placeholder': 'Masukkan username'
            }
        )
    )

    password = forms.CharField(
        max_length = 100, 
        widget = forms.PasswordInput(
            attrs = {
                'class': 'form-control',
				'placeholder': 'Masukkan password'
            }
        )
    )

userauth/views.py
from django.shortcuts import render, redirect, resolve_url
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User 

from .forms import AuthForm

# Create your views here.
def userlogin(request):
    if (not request.user.is_anonymous):
	    return redirect(resolve_url('main:home'))

    form = AuthForm(request.POST or None)
    context = {
        'Form': form,
        'isError': False,
        'Error': '',
    }

    if (request.method == "POST"):
        account = authenticate(
            username = request.POST['nama'],
            password = request.POST['password'],
        )

        if (account == None):
            context['isError'] = True
            context['Error'] = 'Autentikasi gagal'
            context['Form'] = AuthForm()
            return render(request, 'userauth/login.html', context)
        else:
            login(request, account)
            return redirect(resolve_url('main:home'))

    return render(request, 'userauth/login.html', context)

def userregister(request):
    if (not request.user.is_anonymous):
	    return redirect(resolve_url('main:home'))

    form = AuthForm(request.POST or None)
    context = {
        'Form': form,
        'isError': False,
        'Error': '',
    }

    if (request.method == "POST"):
        account = None
        try:
            account = User.objects.get(username = request.POST['nama'])
        except:
            account = None
        if (account == None):
            new_account = User.objects.create_user(request.POST['nama'], '', request.POST['password'])
            new_account.save()
            login(request, new_account)
            return redirect(resolve_url('main:home'))
        else:
            context['isError'] = True
            context['Error'] = 'Sudah ada akun dengan username ' + request.POST['nama']
            context['Form'] = AuthForm()
            return render(request, 'userauth/register.html', context)

    return render(request, 'userauth/register.html', context)

def userlogout(request):
    logout(request)
    return redirect(resolve_url('main:home'))

userauth/templates/userauth/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
<br><br><br><br>
<section id="login">    
    <h1 class="big-text text-center">Login</h1>
    <div class="container" style="max-width:60%">
        <div class="card">
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
            
                    <div class="form-group">
                        <label for="id_nama">Username:</label>
                        {{Form.nama}}
                    </div>
            
                    <div class="form-group">
                        <label for="id_password">Password:</label>
                        {{Form.password}}
                    </div>
                    {% if isError %}
                        <p style="color:red">{{Error}}</p>
                    {% endif %}
                    <button type="submit" class="btn btn-success btn-block">Login</button>
                </form>
                <p>Belum punya akun? <a href="{% url 'userauth:register' %}#register">Register</a></p>
            </div>
        </div>
    </div>
</section>

<br><br><br><br><br><br>

{% endblock content %}

userauth/templates/userauth/register.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Register</title>
{% endblock meta %}

{% block content %}
<br><br><br><br>
<section id="register">    
    <h1 class="big-text text-center">Register</h1>
    <div class="container" style="max-width:60%">
        <div class="card">
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
            
                    <div class="form-group">
                        <label for="id_nama">Username:</label>
                        {{Form.nama}}
                    </div>
            
                    <div class="form-group">
                        <label for="id_password">Password:</label>
                        {{Form.password}}
                    </div>
                    {% if isError %}
                        <p style="color:red">{{Error}}</p>
                    {% endif %}
                    <button type="submit" class="btn btn-success btn-block">Register</button>
                    <p>Sudah punya akun? <a href="{% url 'userauth:login' %}#login">Login</a></p>
                </form>
            </div>
        </div>
    </div>
</section>


<br><br><br><br><br><br>

{% endblock content %}