formulir/urls.py
from django.urls import path

from . import views

app_name = 'formulir'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('delete/<int:delete_id>/', views.delete, name='delete'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

story/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('aboutme/', include('aboutme.urls')),
    path('experience/', include('experience.urls')),
    path('story1/', include('story1.urls')),
    path('kuliah/', include('kuliah.urls')),
    path('kegiatan/', include('formulir.urls')),
    path('accordion/', include('accordion.urls')),
    path('story8/', include('story8.urls')),
    path('userauth/', include('userauth.urls')),
]

formulir/models.py
from django.db import models

# Create your models here.

class Formulir(models.Model):
    list_hari = (
        ('Senin', 'Senin'),
        ('Selasa', 'Selasa'),
        ('Rabu', 'Rabu'),
        ('Kamis', 'Kamis'),
        ('Jum\'at', 'Jum\'at'),
        ('Sabtu', 'Sabtu'),
        ('Minggu', 'Minggu'),
    )

    Kegiatan    = models.CharField(max_length=50)
    Hari        = models.CharField(max_length=50, choices=list_hari, default='Senin')
    Tanggal     = models.DateField(max_length=50)
    Jam         = models.TimeField(max_length=50)
    Tempat      = models.CharField(max_length=50)
    Kategori    = models.CharField(max_length=50)

    def __str__(self):
        return "{}.{}".format(self.id, self.Kegiatan)


class Peserta(models.Model):
    Nama        = models.CharField(max_length=50)
    Kegiatan    = models.ForeignKey(Formulir, on_delete = models.CASCADE)

    def __str__(self):
        return self.Nama

formulir/forms.py
from django import forms
from .models import Formulir, Peserta

class FormulirForm(forms.ModelForm):
    class Meta:
        model = Formulir

        fields = [
            'Kegiatan',
            'Hari',
            'Tanggal',
            'Jam',
            'Tempat',
            'Kategori',
        ]

        widgets = {
            'Kegiatan': forms.TextInput(
                attrs = {
                    'class' : 'form-control',
                    'place-holder' : 'Kegiatan'
                }
            ),

            'Hari' : forms.Select(
                attrs = {
                    'class' : 'form-control'
                }
            ),

            'Tanggal': forms.TextInput(
                attrs = {
                    'class' : 'form-control form-coloumn',
                    'type' : 'date'
                }
            ),

            'Jam' : forms.TextInput(
                attrs = {
                    'class' : 'form-control',
                    'type' : 'time'
                }   
            ),

            'Tempat' : forms.TextInput(
                attrs = {
                    'class' : 'form-control',
                    'place-holder' : 'ex : Warnet'
                }
            ),

            'Kategori' : forms.TextInput(
                attrs = {
                'class' : 'form-control',
                'place-holder' : 'ex : Belajar'
                }
            ),   
        }

class PesertaForm(forms.ModelForm):
    class Meta:
        model = Peserta
        fields = [
            'Nama',
            'Kegiatan',
        ]

        widgets = {
            'Nama': forms.TextInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'Tambahkan peserta'
                }
            )
        }

formulir/views.py
from django.shortcuts import render, redirect
from .models import Formulir, Peserta
from .forms import FormulirForm, PesertaForm


# Create your views here.
def index(request):
    semua_kegiatan = Formulir.objects.all()
    form_peserta = PesertaForm()
    list_peserta = [[i, Peserta.objects.filter(Kegiatan=i)] for i in semua_kegiatan]

    context = {
        'semua_kegiatan' : semua_kegiatan,
        'form_peserta' : form_peserta,
        'list_peserta' : list_peserta,
    }

    return render(request, 'kegiatan/index.html', context)

def create(request):
    kegiatan_form = FormulirForm(request.POST or None)
    if request.method == 'POST':
        if kegiatan_form.is_valid():
            kegiatan_form.save()
            
            return redirect('formulir:index')
    
    context = {
        'kegiatan_form' : kegiatan_form,
    }

    return render(request, 'kegiatan/create.html', context)

def delete(request, delete_id):
    Formulir.objects.filter(id=delete_id).delete()
    return redirect('formulir:index')


def addpeserta(request):
    form = PesertaForm(request.POST or None)
    if (request.method == 'POST'):
        if (form.is_valid):
            form.save()
    return redirect('formulir:index')

def deletepeserta(request, delete_id):
    Peserta.objects.get(id=delete_id).delete()
    return redirect('formulir:index')

formulir/templates/kegiatan/create.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Tambah Kegiatan</title>
{% endblock meta %}

{% block content %}
<br><br><br><br>
<section>
    <div class="container">
    <h1 style="text-align:center">Tambah Kegiatan</h1>
        <form method='POST'>
            {% csrf_token %}
            <table>
                {{kegiatan_form.as_table}}
            </table>
            <button class="btn btn-primary" type="Submit">Tambahkan</button>
        </form>
    </div>
</section>


<br><br><br><br><br><br>
{% endblock content %}

formulir/templates/kegiatan/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Kegiatan</title>
{% endblock meta %}

{% block content %}
<br><br><br><br>
<section>
    <div class="container">
        <h1 style="text-align:center">Daftar Kuliah</h1>
        <div class="table-responsive-lg">
            {% for kegiatan in semua_kegiatan %}
            <table class="table table-striped">
                <tbody>
                    <tr>
                        <td>Kegiatan</td>
                        <td>{{kegiatan.Kegiatan}}</td>
                    </tr>
                    <tr>
                        <td>Hari</td>
                        <td>{{kegiatan.Hari}}</td>
                    </tr>
                    <tr>
                        <td>Tanggal</td>
                        <td>{{kegiatan.Tanggal}}</td>
                    </tr>
                    <tr>
                        <td>Jam</td>
                        <td>{{kegiatan.Jam}}</td>
                    </tr>
                    <tr>
                        <td>Tempat</td>
                        <td>{{kegiatan.Tempat}}</td>
                    </tr>
                    <tr>
                        <td>Kategori</td>
                        <td>{{kegiatan.Kategori}}</td>
                    </tr>
                    <tr>
                        <td colspan="2" style="text-align: center;"><a class="btn btn-danger" href="{% url 'formulir:delete' kegiatan.id%}" title="">Hapus</a></td>
                    </tr>
                </tbody>
            </table>
            <br><br>
            {% endfor %}
        </div>
        <a class="btn btn-primary" href="{% url 'formulir:create' %}">Tambah Kegiatan</a>
    </div>
</section>


<br><br><br><br><br><br>
{% endblock content %}