kuliah/urls.py
from django.urls import path

from . import views

app_name = 'kuliah'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('delete/<int:delete_id>/', views.delete, name='delete'),
    path('detail/<int:detail_id>/', views.detail, name='detail'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

story/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('aboutme/', include('aboutme.urls')),
    path('experience/', include('experience.urls')),
    path('story1/', include('story1.urls')),
    path('kuliah/', include('kuliah.urls')),
    path('kegiatan/', include('formulir.urls')),
    path('accordion/', include('accordion.urls')),
    path('story8/', include('story8.urls')),
    path('userauth/', include('userauth.urls')),
]

kuliah/models.py
from django.db import models
from .validator import sks_validator, semester_validator

# Create your models here.


class Kuliah(models.Model):
    Mata_Kuliah       = models.CharField(max_length = 100)
    Dosen_Pengajar    = models.CharField(max_length = 100)
    Jumlah_SKS        = models.CharField(
        max_length = 1,
        validators = [sks_validator]
        )
    Deskripsi         = models.TextField()
    Ruang_Kelas       = models.CharField(max_length = 100)
    Semester          = models.CharField(
        max_length = 1,
        validators = [semester_validator]
        )

    def __str__(self):
        return "{}.{}".format(self.id, self.Mata_Kuliah)

kuliah/forms.py
from django import forms
from .models import Kuliah

class KuliahForm(forms.ModelForm):
    class Meta:
        model = Kuliah
        fields = [
            'Mata_Kuliah',
            'Dosen_Pengajar',
            'Jumlah_SKS',
            'Deskripsi',
            'Ruang_Kelas',
            'Semester',
        ]

kuliah/views.py
from django.shortcuts import render, redirect

from .forms import KuliahForm
from .models import Kuliah


def index(request):
    semua_kuliah = Kuliah.objects.all()

    context = {
        'semua_kuliah':semua_kuliah,
    }

    return render(request, 'html/index.html', context)

def create(request):
    kuliah_form = KuliahForm(request.POST or None)
    if request.method == 'POST':
        if kuliah_form.is_valid():
            kuliah_form.save()
            
            return redirect('kuliah:index')
    
    context = {
        'kuliah_form':kuliah_form,
    }

    return render(request, 'html/create.html', context)

def delete(request, delete_id):
    Kuliah.objects.filter(id=delete_id).delete()
    return redirect('kuliah:index')

def detail(request, detail_id):
    kuliah_detail = Kuliah.objects.get(id=detail_id)
    context = {
        'kuliah_detail':kuliah_detail,
    }
    
    return render(request, 'html/detail.html', context)

kuliah/templates/html/create.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Kuliah</title>
{% endblock meta %}

{% block content %}
<br><br><br><br>
<section>
    <div class="container">
    <h1 style="text-align:center">Tambah Mata Kuliah</h1>
        <form method='POST'>
            {% csrf_token %}
            <table>
                {{kuliah_form.as_table}}
            </table>
            <button class="btn btn-primary" type="Submit">Tambahkan</button>
        </form>
    </div>
</section>

<br><br><br><br><br><br>
{% endblock content %}

kuliah/templates/html/detail.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Kuliah</title>
{% endblock meta %}

{% block content %}
<br><br><br><br>
<section>
    <div class="container">
        <h1 style="text-align:center">Mata Kuliah</h1>
        <div class="table-responsive-lg">
            <table class="table table-striped">
                <tr>
                    <th scope="col">Mata Kuliah</th>
                    <td>{{kuliah_detail.Mata_Kuliah}}</td>
                </tr>
                <tr>
                    <th scope="col">Dosen Pengajar</th>
                    <td>{{kuliah_detail.Dosen_Pengajar}}</td>
                </tr>
                <tr>
                    <th scope="col">Deskripsi</th>
                    <td>{{kuliah_detail.Deskripsi}}</td>
                </tr>
                <tr>
                    <th scope="col">Jumlah SKS</th>
                    <td>{{kuliah_detail.Jumlah_SKS}}</td>
                </tr>
                <tr>
                    <th scope="col">Ruang Kelas</th>
                    <td>{{kuliah_detail.Ruang_Kelas}}</td>
                </tr>
                <tr>
                    <th scope="col">Semester</th>
                    <td>{{kuliah_detail.Semester}}</td>
                </tr>
            </table>
        </div>
    </div>
</section>
<br><br><br><br><br><br>
{% endblock content %}

kuliah/templates/html/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Mata Kuliah</title>
{% endblock meta %}

{% block content %}
<br><br><br><br>
<section>
    <div class="container">
        <h1 style="text-align:center">Daftar Kuliah</h1>
        <div class="table-responsive-lg">
            <table class="table table-striped">
        <thead>
            <tr>
            <th scope="col">#</th>
            <th scope="col">Mata Kuliah</th>
            <th scope="col">Hapus</th>
            </tr>
        </thead>
        <tbody>
            {% for matkul in semua_kuliah %}
            <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td><a href="{% url 'kuliah:detail' matkul.id%}" title="">{{matkul.Mata_Kuliah}}</a></td>
            <td><a class="btn btn-danger" href="{% url 'kuliah:delete' matkul.id%}" title="">Hapus</a></td>
            </tr>
            {% endfor %}
        </tbody>
        </table>
        </div>
    <a class="btn btn-primary" href="{% url 'kuliah:create' %}">Tambah</a>
    </div>
</section>
<br><br><br><br><br><br>

{% endblock content %}